From c8644e2e78de0fd5f548d66cda156012d07bcae4 Mon Sep 17 00:00:00 2001
From: Bastian Blank <waldi@debian.org>
Date: Mon, 21 Nov 2016 19:10:46 +0100
Subject: Make Azure datasource run without root

Forwarded: https://bugs.launchpad.net/cloud-init/+bug/1536961
---
 cloudinit/sources/DataSourceAzure.py | 13 +++++++++----
 1 file changed, 9 insertions(+), 4 deletions(-)

diff --git a/cloudinit/sources/DataSourceAzure.py b/cloudinit/sources/DataSourceAzure.py
index 22f9004..349988f 100644
--- a/cloudinit/sources/DataSourceAzure.py
+++ b/cloudinit/sources/DataSourceAzure.py
@@ -217,10 +217,15 @@ class DataSourceAzureNet(sources.DataSource):
             LOG.debug("using files cached in %s", ddir)
 
         # azure / hyper-v provides random data here
-        seed = util.load_file("/sys/firmware/acpi/tables/OEM0",
-                              quiet=True, decode=False)
-        if seed:
-            self.metadata['random_seed'] = seed
+        try:
+            seed = util.load_file("/sys/firmware/acpi/tables/OEM0",
+                                  quiet=True, decode=False)
+            if seed:
+                self.metadata['random_seed'] = seed
+
+        # Don't fail if we can't read this file
+        except IOError:
+            pass
 
         # now update ds_cfg to reflect contents pass in config
         user_ds_cfg = util.get_cfg_by_path(self.cfg, DS_CFG_PATH, {})
